### ISSUE TITLE
Implement basic index page

### ISSUE THREAD

**Issue by arg2009** [arg2009/hangman-evolution#1]

**Comment by ghost** [comment]
hey, lyza here.

**Comment by arg2009** [comment]
> hey, lyza here.

Hi Lyza!

Welcome! I have sent you an invitation to collaborate on this project.

This is the issue I have assigned to you! :smile: 
https://github.com/arg2009/hangman-evolution/issues/3

Let me know if you want help doing it together or if you want to try it yourself first!
